// try {
//   //在此运行代码
// }
// catch(err){
//   //在此处理错误
// }

var array = null;
try {
  console.log('array[0]: ', array[0]);
} catch(err) {
  console.log('err: ', err);
}